// Generates one Storybook story per component by reusing the demos that already
// power the docs site (components/docs/demos.tsx + registry.tsx).
//
//   node scripts/gen-stories.mjs
//
// Components in RICH_STORIES are skipped here because they ship hand-written,
// arg-driven stories (controls for variants/sizes/states). Everything else gets
// a generated "Showcase" story so dev/QA always have full coverage in Storybook.

import { readFileSync, writeFileSync, mkdirSync, readdirSync, rmSync } from "node:fs";
import { fileURLToPath } from "node:url";
import path from "node:path";

const root = path.dirname(path.dirname(fileURLToPath(import.meta.url)));
const registryPath = path.join(root, "components/docs/registry.tsx");
const outDir = path.join(root, "stories/generated");

// Hand-written, controls-rich stories live in stories/ — do not auto-generate these.
const RICH_STORIES = new Set([
  "button",
  "badge",
  "input",
  "textarea",
  "alert",
  "switch",
  "checkbox",
]);

const src = readFileSync(registryPath, "utf8");

// Each registry entry exposes slug → name → category → Demo in that order.
const entryRe =
  /slug:\s*"([^"]+)"[\s\S]*?name:\s*"([^"]+)"[\s\S]*?category:\s*"([^"]+)"[\s\S]*?Demo:\s*(\w+)/g;

const entries = [];
let m;
while ((m = entryRe.exec(src)) !== null) {
  const [, slug, name, category, demo] = m;
  entries.push({ slug, name, category, demo });
}

if (entries.length === 0) {
  throw new Error("No registry entries parsed — check registry.tsx shape.");
}

// Start clean so removed components don't leave orphan stories behind.
rmSync(outDir, { recursive: true, force: true });
mkdirSync(outDir, { recursive: true });

let written = 0;
for (const { slug, name, category, demo } of entries) {
  if (RICH_STORIES.has(slug)) continue;

  const file = `${demo.replace(/Demo$/, "")}.stories.tsx`;
  const story = `// AUTO-GENERATED by scripts/gen-stories.mjs — do not edit by hand.
// Edit the source demo in components/docs/demos.tsx instead, then re-run \`pnpm gen:stories\`.
import type { Meta, StoryObj } from "@storybook/nextjs-vite";

import { ${demo} } from "@/components/docs/demos";

const meta = {
  title: "${category}/${name}",
  component: ${demo},
  parameters: { layout: "centered" },
} satisfies Meta<typeof ${demo}>;

export default meta;
type Story = StoryObj<typeof meta>;

export const Showcase: Story = {};
`;

  writeFileSync(path.join(outDir, file), story);
  written += 1;
}

const skipped = entries.filter((e) => RICH_STORIES.has(e.slug)).map((e) => e.slug);
console.log(
  `Generated ${written} stories in stories/generated/ ` +
    `(skipped ${skipped.length} rich: ${skipped.join(", ")}). ` +
    `Registry total: ${entries.length}.`,
);

// Sanity: surface any rich slug that no longer exists in the registry.
const slugs = new Set(entries.map((e) => e.slug));
for (const s of RICH_STORIES) {
  if (!slugs.has(s)) console.warn(`⚠ RICH_STORIES contains "${s}" not found in registry.`);
}

// Keep the generated dir listing stable/visible in CI logs.
console.log("Files:", readdirSync(outDir).sort().join(", "));
