#!/usr/bin/env node
/**
 * sync-tokens.mjs — regenerate src/app/globals.css from the Figma token snapshot.
 *
 * Source of truth: design/variables-export.json (LazyYsync export, 1,806 variables).
 * Output:          src/app/globals.css  (@theme inline + :root + .dark)
 *
 * The shadcn/ui collection (35 vars) carries resolved sRGB values per mode
 * (light mode / dark mode). We convert those to OKLCh — the same color space
 * shadcn/ui ships in — and emit every token, exactly as the export contains them.
 *
 * Usage:
 *   node scripts/sync-tokens.mjs            # write src/app/globals.css
 *   node scripts/sync-tokens.mjs --check    # verify only, write nothing (CI)
 */

import { readFileSync, writeFileSync, mkdirSync } from "node:fs";
import { dirname, resolve } from "node:path";
import { fileURLToPath } from "node:url";

const ROOT = resolve(dirname(fileURLToPath(import.meta.url)), "..");
const SRC = resolve(ROOT, "design/variables-export.json");
const OUT = resolve(ROOT, "src/app/globals.css");
const EXPECTED_VARS = 1806;
const CHECK_ONLY = process.argv.includes("--check");

// Every color token in the shadcn/ui collection is emitted, in source order
// (canonical tokens first, then background-color / semantic-* extras). The
// ordered name list is derived from the JSON after load — never hand-maintained,
// so the output always matches exactly what the export contains: no more, no less.

// ── sRGB → OKLCh ──────────────────────────────────────────────────────────
const toLinear = (c) => (c <= 0.04045 ? c / 12.92 : Math.pow((c + 0.055) / 1.055, 2.4));

function rgbToOklch({ r, g, b, a = 1 }) {
  const lr = toLinear(r), lg = toLinear(g), lb = toLinear(b);
  const l = 0.4122214708 * lr + 0.5363325363 * lg + 0.0514459929 * lb;
  const m = 0.2119034982 * lr + 0.6806995451 * lg + 0.1073969566 * lb;
  const s = 0.0883024619 * lr + 0.2817188376 * lg + 0.6299787005 * lb;
  const l_ = Math.cbrt(l), m_ = Math.cbrt(m), s_ = Math.cbrt(s);
  const L = 0.2104542553 * l_ + 0.793617785 * m_ - 0.0040720468 * s_;
  const A = 1.9779984951 * l_ - 2.428592205 * m_ + 0.4505937099 * s_;
  const B = 0.0259040371 * l_ + 0.7827717662 * m_ - 0.808675766 * s_;
  let C = Math.sqrt(A * A + B * B);
  let H = (Math.atan2(B, A) * 180) / Math.PI;
  if (H < 0) H += 360;
  return { L, C, H, a };
}

const num = (x) => Number(x.toFixed(3)).toString();

function oklchString(rgb) {
  const { L, C, H, a } = rgbToOklch(rgb);
  const achromatic = C < 0.0005;
  const core = achromatic ? `${num(L)} 0 0` : `${num(L)} ${num(C)} ${num(H)}`;
  return a < 1 ? `oklch(${core} / ${Math.round(a * 100)}%)` : `oklch(${core})`;
}

// ── Load + validate ───────────────────────────────────────────────────────
const data = JSON.parse(readFileSync(SRC, "utf8"));
if (data.variables.length !== EXPECTED_VARS) {
  console.error(
    `✗ token count drift: expected ${EXPECTED_VARS}, found ${data.variables.length}. ` +
      `Re-export from Figma or update EXPECTED_VARS intentionally.`
  );
  process.exit(1);
}

const shadcnVars = data.variables.filter((v) => v.collectionName === "shadcn/ui");
const ORDER = shadcnVars.map((v) => v.name); // all 35, in source order
const shadcn = new Map(shadcnVars.map((v) => [v.name, v.valuesByMode]));

const modeValue = (name, mode) => {
  const byMode = shadcn.get(name);
  if (!byMode || !byMode[mode]) throw new Error(`missing ${name} / ${mode}`);
  return oklchString(byMode[mode].value);
};

// ── Build globals.css ─────────────────────────────────────────────────────
const pad = (s) => s.padEnd(37);
const themeLines = ORDER.map((n) => `  ${pad(`--color-${n}:`)} var(--${n});`).join("\n");
const rootLines = ORDER.map((n) => `  ${pad(`--${n}:`)} ${modeValue(n, "light mode")};`).join("\n");
const darkLines = ORDER.map((n) => `  ${pad(`--${n}:`)} ${modeValue(n, "dark mode")};`).join("\n");

const css = `/* AUTO-GENERATED by scripts/sync-tokens.mjs — do not edit by hand.
   Source: design/variables-export.json (${EXPECTED_VARS} variables, ${ORDER.length} shadcn/ui tokens). Run \`pnpm sync:tokens\` to regenerate. */

@import "tailwindcss";
@import "tw-animate-css";

@custom-variant dark (&:is(.dark *));

@theme inline {
${themeLines}
  ${pad("--radius-sm:")} calc(var(--radius) - 4px);
  ${pad("--radius-md:")} calc(var(--radius) - 2px);
  ${pad("--radius-lg:")} var(--radius);
  ${pad("--radius-xl:")} calc(var(--radius) + 4px);
}

:root {
  ${pad("--radius:")} 0.625rem;
${rootLines}
}

.dark {
${darkLines}
}

@layer base {
  * {
    @apply border-border outline-ring/50;
  }
  body {
    @apply bg-background text-foreground;
  }
}
`;

if (CHECK_ONLY) {
  console.log(`✓ ${EXPECTED_VARS} variables present · ${ORDER.length} semantic tokens resolved (check mode, nothing written)`);
  process.exit(0);
}

mkdirSync(dirname(OUT), { recursive: true });
writeFileSync(OUT, css, "utf8");
console.log(`✓ wrote ${OUT}`);
console.log(`  ${EXPECTED_VARS} variables · ${ORDER.length} semantic tokens → :root + .dark`);
